import React from "react";

export default function TermsConditions() {
  return (
    <div>
      <div className="container">
        <div className="row">
          <div className="col-12">
            <h4>Terms & conditions</h4>
            <p>
              <ol>
                <li>
                  The old gold that you bring for exchange must be in plain gold
                  format (without any gemstones or diamonds). Other than plain
                  gold jewellery, gold coins, biscuits or bars are also
                  accepted.
                </li>
                <li>
                  The jewellery that you exchange it for can be any jewellery
                  item from CaratLane designs belonging to plain gold jewellery,
                  diamond and gemstone jewellery and platinum jewellery
                  categories.
                </li>
                <li>
                  Old gold can be exchanged for any diamond studded jewellery
                  (upto 18kt Gold). For exchange to 22 KT Jewellery or Loose
                  diamond, a 4% standard deduction on Old gold value will be
                  applicable. You cannot exchange your old gold for cash or gold
                  coins.
                </li>
                <li>
                  Once your exchange value is computed, you can buy any
                  CaratLane jewellery of similar or higher value by paying the
                  excess in cash or card.
                </li>
                <li>
                  A declaration form has to be signed by you stating the weight
                  of gold being exchanged. This form states that you have
                  willingly given the gold for cutting/ melting. It also
                  mentions that the gold given by you will not be returned and
                  the purity reading generated by the Karatmeter will be
                  acceptable to you.
                </li>
                <li>
                  In this exchange programme, you will not be eligible for 15
                  day Money-Back guarantee unlike regular purchases made from
                  CaratLane. Lifetime Exchange policy will be applicable.
                </li>
                <li>
                  The gold jewellery you bring for exchange must be either 14Kt,
                  18Kt or 22Kt. 2% deduction is only applicable on jewellery
                  that is 18Kt or above.
                </li>
              </ol>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
